name: Build Kivy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_SDK_ROOT: /opt/android-sdk
    steps:
      - uses: actions/checkout@v4

      - name: Clean old build caches
        run: |
          rm -rf .buildozer .p4a

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel python3-venv git zip unzip openjdk-17-jdk autoconf automake libtool libltdl-dev pkg-config libffi-dev libssl-dev

      - name: Install pip dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython==0.29.36

      - name: Download Android SDK commandline tools
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          cd /opt/android-sdk/cmdline-tools
          sudo wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          sudo unzip cmdline-tools.zip -d tmp
          sudo mv tmp/cmdline-tools latest
          sudo rm -rf tmp
          sudo rm cmdline-tools.zip
          sudo chown -R $USER:$USER /opt/android-sdk

      - name: Install Android SDK Build Tools and Platform Tools
        run: |
          export PATH=/opt/android-sdk/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=/opt/android-sdk --licenses
          sdkmanager --sdk_root=/opt/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-33"

      - name: Shim legacy sdkmanager path
        run: |
          # Cria diretório legacy
          mkdir -p /opt/android-sdk/tools/bin
          # Linka sdkmanager moderno no local legacy
          ln -sf /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager /opt/android-sdk/tools/bin/sdkmanager
          # Opcional: linka também o avdmanager
          ln -sf /opt/android-sdk/cmdline-tools/latest/bin/avdmanager /opt/android-sdk/tools/bin/avdmanager
          # Cria source.properties fake para scripts legacy
          echo "Pkg.Revision=26.1.1" > /opt/android-sdk/tools/source.properties

      - name: Debug SDK structure
        run: |
          ls -l /opt/android-sdk/tools/bin
          ls -l /opt/android-sdk/cmdline-tools/latest/bin

      - name: Build APK
        run: |
          export PATH=/opt/android-sdk/platform-tools:/opt/android-sdk/build-tools/34.0.0:/opt/android-sdk/cmdline-tools/latest/bin:$PATH
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
